In [2]:
import pandas as pd
import numpy as np

In [3]:
data={
    "department":["it","it","it","it","finance","hr"],
    "salary":[10000,20000,30000,40000,50000,60000],
    "employee":[1,2,3,4,5,6],
    "experience":[1,2,3,4,5,6]
}
df=pd.DataFrame(data)
df

  department  salary  employee  experience
0         it   10000         1           1
1         it   20000         2           2
2         it   30000         3           3
3         it   40000         4           4
4    finance   50000         5           5
5         hr   60000         6           6

In [4]:
#groupby
avg_salary=df.groupby("department")["salary"].mean()
avg_salary

department
finance    50000.0
hr         60000.0
it         25000.0
Name: salary, dtype: float64

In [5]:
max_salary=df.groupby("department")["salary"].max()
max_salary

department
finance    50000
hr         60000
it         40000
Name: salary, dtype: int64

In [6]:
total_salary=df.groupby("department")["salary"].sum()
total_salary

department
finance     50000
hr          60000
it         100000
Name: salary, dtype: int64

In [7]:
emp_count= df.groupby("department")["employee"].count()
emp_count

department
finance    1
hr         1
it         4
Name: employee, dtype: int64

In [8]:
avg_salary_experience= df.groupby("department")[["salary","experience"]].mean()
avg_salary_experience

             salary  experience
department
finance     50000.0         5.0
hr          60000.0         6.0
it          25000.0         2.5

In [9]:
#merge &join
employee =pd.DataFrame({
    "id":[1,2,3,4],
    "name":["a","b","c","d"],
    "department":["it","it","hr","hr"]
})
departemnts=pd.DataFrame({
    "id":[1,2,3,4],
    "salary":[10000,20000,30000,40000],
    "department":["it","hr","finance","it"]
})
result=pd.merge(employee,departemnts,on="id")
result

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [10]:
inner_join =pd.merge(employee,departemnts,how="inner",on="id")
inner_join

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [11]:
left_join=pd.merge(employee,departemnts,how="left",on="id")
left_join

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [12]:
right_join=pd.merge(employee,departemnts,how="right",on="id")
right_join

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [13]:
#find records exist in one only 
merged=pd.merge(employee,departemnts,how="outer",indicator=True)
merged

   id name department   salary      _merge
0   1    a         it  10000.0        both
1   2  NaN         hr  20000.0  right_only
2   2    b         it      NaN   left_only
3   3  NaN    finance  30000.0  right_only
4   3    c         hr      NaN   left_only
5   4    d         hr      NaN   left_only
6   4  NaN         it  40000.0  right_only

In [14]:
#concatenation 
df1=pd.DataFrame({
    "id":[1,2,3,4],
    "name":["a","b","c","d"],
    "salary":[10000,20000,30000,40000],
    "department":["it","it","hr","hr"]
})
df2=pd.DataFrame({
    "id":[1,2,3,4],
    "name":["e","f","g","h"],
    "salary":[50000,60000,70000,80000],
    "department":["it","it","hr","hr"]
})
row_concat=pd.concat([df1,df2])
row_concat

   id name  salary department
0   1    a   10000         it
1   2    b   20000         it
2   3    c   30000         hr
3   4    d   40000         hr
0   1    e   50000         it
1   2    f   60000         it
2   3    g   70000         hr
3   4    h   80000         hr

In [15]:
column_concat=pd.concat([df1,df2],axis=1)
column_concat

   id name  salary department  id name  salary department
0   1    a   10000         it   1    e   50000         it
1   2    b   20000         it   2    f   60000         it
2   3    c   30000         hr   3    g   70000         hr
3   4    d   40000         hr   4    h   80000         hr

In [16]:
concatenate = pd.concat([df1,df2],ignore_index=True)
concatenate

   id name  salary department
0   1    a   10000         it
1   2    b   20000         it
2   3    c   30000         hr
3   4    d   40000         hr
4   1    e   50000         it
5   2    f   60000         it
6   3    g   70000         hr
7   4    h   80000         hr

In [17]:
keys_concat=pd.concat([df1,df2],keys=["df1","df2"])
keys_concat

       id name  salary department
df1 0   1    a   10000         it
    1   2    b   20000         it
    2   3    c   30000         hr
    3   4    d   40000         hr
df2 0   1    e   50000         it
    1   2    f   60000         it
    2   3    g   70000         hr
    3   4    h   80000         hr

In [18]:
#pivot table
data={
    "sales":[10,20,30,40],
    "price":[100,200,300,400],
    "product_id":[1,2,3,4],
    "product_name":["a","b","c","d"],
    "region":["north","south","east","west"]
}
df= pd.DataFrame(data)
df

   sales  price  product_id product_name region
0     10    100           1            a  north
1     20    200           2            b  south
2     30    300           3            c   east
3     40    400           4            d   west

In [19]:
#create pivot table showing total sales by region 
pivot_table=df.pivot_table(index="region",values="sales",aggfunc="sum")
pivot_table

        sales
region
east       30
north      10
south      20
west       40

In [20]:
#pivot tables with regions as rows and products as columns
pivot_table=df.pivot_table(index="region",columns="product_name",values="sales",aggfunc="sum")
pivot_table

product_name     a     b     c     d
region
east           NaN   NaN  30.0   NaN
north         10.0   NaN   NaN   NaN
south          NaN  20.0   NaN   NaN
west           NaN   NaN   NaN  40.0

In [21]:
#pivot table showing average sales for each product in each region 
pivot1=pd.pivot_table(df,index=["region","product_name"],values="sales",aggfunc="mean")
pivot1

                     sales
region product_name
east   c              30.0
north  a              10.0
south  b              20.0
west   d              40.0

In [23]:
#datetime
#convert date column from strring column to datetime fromat 
dates = pd.date_range(start= "2023-01-01",periods=10,freq='D')
ts=pd.DataFrame({"date":dates,"sales":[189,276,356,456,235,678,767,800,999,1000]})
ts

        date  sales
0 2023-01-01    189
1 2023-01-02    276
2 2023-01-03    356
3 2023-01-04    456
4 2023-01-05    235
5 2023-01-06    678
6 2023-01-07    767
7 2023-01-08    800
8 2023-01-09    999
9 2023-01-10   1000

In [24]:
#extract year month and day
ts['year']=ts['date'].dt.year
ts['month']=ts['date'].dt.month
ts['day']=ts['date'].dt.day
ts

        date  sales  year  month  day
0 2023-01-01    189  2023      1    1
1 2023-01-02    276  2023      1    2
2 2023-01-03    356  2023      1    3
3 2023-01-04    456  2023      1    4
4 2023-01-05    235  2023      1    5
5 2023-01-06    678  2023      1    6
6 2023-01-07    767  2023      1    7
7 2023-01-08    800  2023      1    8
8 2023-01-09    999  2023      1    9
9 2023-01-10   1000  2023      1   10

In [25]:
#set date column as index and calculate a rolling 3 day average 
ts.set_index("date").rolling(3).mean()

                 sales    year  month  day
date
2023-01-01         NaN     NaN    NaN  NaN
2023-01-02         NaN     NaN    NaN  NaN
2023-01-03  273.666667  2023.0    1.0  2.0
2023-01-04  362.666667  2023.0    1.0  3.0
2023-01-05  349.000000  2023.0    1.0  4.0
2023-01-06  456.333333  2023.0    1.0  5.0
2023-01-07  560.000000  2023.0    1.0  6.0
2023-01-08  748.333333  2023.0    1.0  7.0
2023-01-09  855.333333  2023.0    1.0  8.0
2023-01-10  933.000000  2023.0    1.0  9.0

In [26]:
#total sales for each product using groupby
total_sales=df.groupby("product_name")["sales"].sum()
total_sales

product_name
a    10
b    20
c    30
d    40
Name: sales, dtype: int64

In [29]:
#highest selling product in each region 
df.groupby(["region","product_name"])["sales"].max()

region  product_name
east    c               30
north   a               10
south   b               20
west    d               40
Name: sales, dtype: int64

In [31]:
#merge  customer and order dataframe using customer id 
customer = pd.DataFrame({
    "customer_id":[1,2,3,4],
    "customer_name":["a","b","c","d"]
})
order=pd.DataFrame({
    "order_id":[1,2,3,4],
    "customer_id":[1,2,3,4],
    "order_date":["2023-01-01","2023-01-02","2023-01-03","2023-01-04"]
})
result=pd.merge(customer,order,how="inner",on="customer_id")
result

   customer_id customer_name  order_id  order_date
0            1             a         1  2023-01-01
1            2             b         2  2023-01-02
2            3             c         3  2023-01-03
3            4             d         4  2023-01-04

In [32]:
#concatenate monthly salesinto single datframes 
df1=pd.DataFrame({
    "date":["2023-01-01","2023-01-02","2023-01-03"],
    "sales":[100,200,300]
})
df2=pd.DataFrame({
    "date":["2023-02-01","2023-02-02","2023-02-03"],
    "sales":[400,500,600]
})
concatenate = pd.concat([df1,df2],ignore_index=True)
concatenate

         date  sales
0  2023-01-01    100
1  2023-01-02    200
2  2023-01-03    300
3  2023-02-01    400
4  2023-02-02    500
5  2023-02-03    600

In [35]:
pivot=pd.pivot_table(df,index="product_name",values="sales",aggfunc="sum")
pivot

              sales
product_name
a                10
b                20
c                30
d                40

In [39]:
#resample daily sales data into weekly sales totals 
sales=pd.DataFrame({
    "date":["2023-01-01","2023-01-02","2023-01-03","2023-01-04","2023-01-05","2023-01-06","2023-01-07","2023-01-08","2023-01-09"],
    "sales":[100,200,300,400,500,600,700,800,900]
})
sales["date"]=pd.to_datetime(sales["date"])
sales=sales.set_index("date")
sales=sales.resample("W").sum()
sales

            sales
date
2023-01-01    100
2023-01-08   3500
2023-01-15    900

In [40]:
#cumulative sales over time 
sales=pd.DataFrame({
    'dates':['2023-01-01','2023-01-02','2023-01-03','2023-01-04','2023-01-05','2023-01-06','2023-01-07','2023-01-08','2023-01-09'],
    'sales':[100,200,300,400,500,600,700,800,900]
})
sales['dates']=pd.to_datetime(sales['dates'])
sales=sales.set_index('dates')
sales=sales.cumsum()
sales

            sales
dates
2023-01-01    100
2023-01-02    300
2023-01-03    600
2023-01-04   1000
2023-01-05   1500
2023-01-06   2100
2023-01-07   2800
2023-01-08   3600
2023-01-09   4500

In [43]:
#fid top3 departments based on avg_salary
df=pd.DataFrame({
    "department":["it","it","it","it","finance","hr"],
    "salary":[10000,20000,30000,40000,50000,60000],
    "employee":[1,2,3,4,5,6],
    "experience":[1,2,3,4,5,6]
})
df.groupby("department")["salary"].mean().nlargest(3)

department
hr         60000.0
finance    50000.0
it         25000.0
Name: salary, dtype: float64

In [44]:
#merge 3 dataframes using common keys 
df1=pd.DataFrame({
    "id":[1,2,3,4],
    "name":["a","b","c","d"],
    "department":["it","it","hr","hr"]
})
df2=pd.DataFrame({
    "id":[1,2,3,4],
    "salary":[10000,20000,30000,40000],
    "department":["it","hr","finance","it"]
})
df3=pd.DataFrame({
    "id":[1,2,3,4],
    "order_id":[1,2,3,4],
    "order_date":["2023-01-01","2023-01-02","2023-01-03","2023-01-04"]
})
result=pd.merge(df1,df2,how="inner",on="id")
result=pd.merge(result,df3,how="inner",on="id")
result

   id name department_x  salary department_y  order_id  order_date
0   1    a           it   10000           it         1  2023-01-01
1   2    b           it   20000           hr         2  2023-01-02
2   3    c           hr   30000      finance         3  2023-01-03
3   4    d           hr   40000           it         4  2023-01-04

In [47]:
#pivot tables with multiple aggreagation
#pivot tables with multiple aggreagation
df_products = pd.DataFrame(data)  # use original product data dict (df was overwritten earlier)
pivot = pd.pivot_table(df_products, index=["product_name","region"], values="sales", aggfunc=["sum","mean"])
pivot
pivot

                      sum  mean
                    sales sales
product_name region
a            north     10  10.0
b            south     20  20.0
c            east      30  30.0
d            west      40  40.0