In [1]:
#assignment questions 
import numpy as np
import pandas as pd

In [2]:
list=[10,20,30,40]
print(pd.Series(list))

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
li=[100,200,300]
labels=["a","b","c"]
print(pd.Series(li,index=labels))

a    100
b    200
c    300
dtype: int64

In [4]:
dict={"x":5,"y":10,"z":15}
print(pd.Series(dict))

x     5
y    10
z    15
dtype: int64

In [5]:
print(dict["y"])

10

In [6]:
data = {
    "name": ["rahul", "priya", "amit", "neha"],
    "age": [22, 21, 23, 22],
    "city": ["pune", "mumbai", "nashik", "delhi"]
}
df=pd.DataFrame(data)
df

    name  age    city
0  rahul   22    pune
1  priya   21  mumbai
2   amit   23  nashik
3   neha   22   delhi

In [7]:
data1=[
    ["rahul",22,"pune"],
    ["priya",21,"mumbai"],
    ["amit",23,"nashik"],
    ["neha",22,"delhi"] 
]
columns=["name","age","city"]
df1=pd.DataFrame(data1, columns=columns)
df1

    name  age    city
0  rahul   22    pune
1  priya   21  mumbai
2   amit   23  nashik
3   neha   22   delhi

In [8]:
df["name"]

0    rahul
1    priya
2     amit
3     neha
Name: name, dtype: object

In [9]:
df[["name","city"]]

    name    city
0  rahul    pune
1  priya  mumbai
2   amit  nashik
3   neha   delhi

In [10]:
df.loc[[0,1]]

    name  age    city
0  rahul   22    pune
1  priya   21  mumbai

In [11]:
df.iloc[2]

name      amit
age         23
city    nashik
Name: 2, dtype: object

In [12]:
marks=[78,85,90,67]
df["marks"]=marks
df

    name  age    city  marks
0  rahul   22    pune     78
1  priya   21  mumbai     85
2   amit   23  nashik     90
3   neha   22   delhi     67

In [13]:
df["course"]=["python","java","python","data science"]
df

    name  age    city  marks        course
0  rahul   22    pune     78        python
1  priya   21  mumbai     85          java
2   amit   23  nashik     90        python
3   neha   22   delhi     67  data science

In [14]:
df2=df.drop(columns=["city"])
df2

    name  age  marks        course
0  rahul   22     78        python
1  priya   21     85          java
2   amit   23     90        python
3   neha   22     67  data science

In [15]:
df3=df.drop(index=1)
df3

    name  age    city  marks        course
0  rahul   22    pune     78        python
2   amit   23  nashik     90        python
3   neha   22   delhi     67  data science

In [16]:
df[df["age"]>22]

   name  age    city  marks  course
2  amit   23  nashik     90  python

In [17]:
df[df["city"]=="pune"]

    name  age  city  marks  course
0  rahul   22  pune     78  python

In [18]:
df[(df["age"]>21) & (df["city"] =="delhi")]

   name  age   city  marks        course
3  neha   22  delhi     67  data science

In [19]:
df= pd.read_csv("student.csv")
df.head(3)

,StudentID,Age,StudyTimeWeekly,Absences,GPA,Gender,Ethnicity,ParentalEducation,Tutoring,ParentalSupport,ClubInvolvement,Sports,Music,Volunteering,GradeClass
0,1001,17,19.833723,7,2.929196,Female,Caucasian,Some College,Yes,Moderate,No,No,Yes,No,C
1,1002,18,15.408756,0,3.042915,Male,Caucasian,High School,No,Low,No,No,No,No,B
2,1003,15,4.210570,26,0.112602,Male,Asian,Bachelor's,No,Moderate,No,No,No,No,F

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6055 entries, 0 to 6054
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          6055 non-null   int64
 1   Age                6055 non-null   int64
 2   StudyTimeWeekly    6055 non-null   float64
 3   Absences           6055 non-null   int64
 4   GPA                6055 non-null   float64
 5   Gender             6055 non-null   object
 6   Ethnicity          6055 non-null   object
 7   ParentalEducation  5645 non-null   object
 8   Tutoring           6055 non-null   object
 9   ParentalSupport    5755 non-null   object
 10  ClubInvolvement    6055 non-null   object
 11  Sports             6055 non-null   object
 12  Music              6055 non-null   object
 13  Volunteering       6055 non-null   object
 14  GradeClass         6055 non-null   object
dtypes: float64(2), int64(3), object(10)
memory usage: 709.7+ KB

In [21]:
df=pd.read_csv("https://api.slingacademy.com/v1/sample-data/files/student-scores.csv")
df.head(3)

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94

In [22]:
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [23]:
df[["first_name","math_score"]]

     first_name  math_score
0          Paul          73
1      Danielle          90
2          Tina          81
3          Tara          71
4       Anthony          84
...         ...         ...
1995       Alan          83
1996     Thomas          89
1997    Madison          97
1998   Brittany          51
1999    Natalie          82

[2000 rows x 2 columns]

In [24]:
df.shape

(2000, 17)

In [25]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

In [26]:
df.dtypes

id                             int64
first_name                    object
last_name                     object
email                         object
gender                        object
part_time_job                   bool
absence_days                   int64
extracurricular_activities      bool
weekly_self_study_hours        int64
career_aspiration             object
math_score                     int64
history_score                  int64
physics_score                  int64
chemistry_score                int64
biology_score                  int64
english_score                  int64
geography_score                int64
dtype: object

In [27]:
print(df["math_score"].max())
print(df["math_score"].min())

100
40

In [28]:
df["math_score"].mean()

np.float64(83.452)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2000 non-null   int64
 1   first_name                  2000 non-null   object
 2   last_name                   2000 non-null   object
 3   email                       2000 non-null   object
 4   gender                      2000 non-null   object
 5   part_time_job               2000 non-null   bool
 6   absence_days                2000 non-null   int64
 7   extracurricular_activities  2000 non-null   bool
 8   weekly_self_study_hours     2000 non-null   int64
 9   career_aspiration           2000 non-null   object
 10  math_score                  2000 non-null   int64
 11  history_score               2000 non-null   int64
 12  physics_score               2000 non-null   int64
 13  chemistry_score             2000 non-null   int64
 14  biology_score               2000 non-null   int64
 15  english_score               2000 non-null   int64
 16  geography_score             2000 non-null   int64
dtypes: bool(2), int64(10), object(5)
memory usage: 238.4+ KB

In [30]:
df.isnull()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
df.isnull().sum()

id                            0
first_name                    0
last_name                     0
email                         0
gender                        0
part_time_job                 0
absence_days                  0
extracurricular_activities    0
weekly_self_study_hours       0
career_aspiration             0
math_score                    0
history_score                 0
physics_score                 0
chemistry_score               0
biology_score                 0
english_score                 0
geography_score               0
dtype: int64

In [32]:
df["total _scores"]=df["math_score"]+df["history_score"]+df["physics_score"]+df["chemistry_score"]+df["biology_score"]+df["english_score"]+df["geography_score"]
df

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total _scores
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,558
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,534
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,578
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,566
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,617

In [33]:
df.dropna()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total _scores
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,558
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,534
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,578
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,566
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,617

In [35]:
df=pd.read_csv("ecommerce_product_dataset.csv")
df

,ProductID,ProductName,Category,Price,Rating,NumReviews,StockQuantity,Discount,Sales,DateAdded
0,1,Headphones,Electronics,400.31,1.7,3772,20,0.08,466,2023-11-08
1,2,Headphones,Electronics,235.03,2.3,2919,663,0.33,1332,2023-09-26
2,3,Smartwatch,Electronics,417.90,1.8,1184,459,0.31,252,2023-10-18
3,4,Smartphone,Electronics,152.70,3.4,2047,475,0.49,1806,2023-12-03
4,5,Laptop,Electronics,394.74,1.8,1267,831,0.23,1508,2023-08-08
...,...,...,...,...,...,...,...,...,...,...
995,996,Throw Blanket,Blankets,207.72,2.3,1973,16,0.46,325,2024-02-11
996,997,Fleece Blanket,Blankets,268.60,3.2,841,201,0.39,1546,2023-06-29
997,998,Throw Blanket,Blankets,92.74,2.8,3454,880,0.02,1295,2023-10-27
998,999,Weighted Blanket,Blankets,152.28,1.3,2850,752,0.34,1962,2023-10-26
999,1000,Throw Blanket,Blankets,136.53,2.0,4055,282,0.38,1089,2024-01-25

In [36]:
df[df["Category"]=="Electronics"]

,ProductID,ProductName,Category,Price,Rating,NumReviews,StockQuantity,Discount,Sales,DateAdded
0,1,Headphones,Electronics,400.31,1.7,3772,20,0.08,466,2023-11-08
1,2,Headphones,Electronics,235.03,2.3,2919,663,0.33,1332,2023-09-26
2,3,Smartwatch,Electronics,417.90,1.8,1184,459,0.31,252,2023-10-18
3,4,Smartphone,Electronics,152.70,3.4,2047,475,0.49,1806,2023-12-03
4,5,Laptop,Electronics,394.74,1.8,1267,831,0.23,1508,2023-08-08
5,6,Headphones,Electronics,93.56,1.3,2435,600,0.48,241,2023-09-19
6,7,Laptop,Electronics,57.86,3.7,1478,427,0.25,1966,2024-05-06
7,8,Laptop,Electronics,201.62,1.7,3073,389,0.10,1795,2023-08-05
8,9,Smartphone,Electronics,485.10,4.1,161,201,0.45,269,2023-06-25
9,10,Smartwatch,Electronics,170.00,3.3,1275,701,0.16,719,2023-10-17
10,11,Laptop,Electronics,274.45,3.3,4859,187,0.27,1064,2024-01-05
11,12,Headphones,Electronics,90.98,1.1,2568,343,0.20,647,2024-04-08
12,13,Headphones,Electronics,107.43,3.8,4514,288,0.30,1513,2023-10-23
13,14,Laptop,Electronics,66.78,4.5,4875,929,0.05,502,2024-04-09
14,15,Smartwatch,Electronics,336.30,3.4,2773,986,0.28,1762,2024-03-01
15,16,Headphones,Electronics,359.49,4.0,502,766,0.13,794,2023-11-16
16,17,Headphones,Electronics,64.34,2.8,863,742,0.24,1020,2024-03-06
17,18,Smartwatch,Electronics,454.71,2.0,1678,170,0.10,524,2024-01-02
18,19,Headphones,Electronics,151.98,1.6,2625,681,0.40,1976,2024-01-28
19,20,Smartwatch,Electronics,403.80,1.7,1981,330,0.16,1371,2023-10-23
20,21,Laptop,Electronics,63.93,1.9,4029,632,0.41,1768,2023-09-25
21,22,Headphones,Electronics,90.68,3.1,4413,676,0.35,1257,2023-12-21
22,23,Smartwatch,Electronics,472.03,2.3,1495,232,0.20,1853,2024-04-19
23,24,Smartwatch,Electronics,133.37,3.0,1636,624,0.50,698,2024-02-18
24,25,Laptop,Electronics,256.31,1.2,3474,637,0.07,1707,2023-11-05
25,26,Smartwatch,Electronics,280.92,3.4,3510,202,0.18,400,2023-09-29
26,27,Laptop,Electronics,190.21,3.5,197,981,0.27,751,2024-01-18
27,28,Smartphone,Electronics,83.85,3.0,2511,348,0.43,763,2023-06-30
28,29,Headphones,Electronics,406.66,2.4,1734,819,0.47,1959,2024-02-03
29,30,Headphones,Electronics,469.00,1.6,4061,297,0.13,1787,2024-01-18
30,31,Laptop,Electronics,491.26,3.1,4976,1,0.50,253,2024-01-22
31,32,Smartphone,Electronics,451.20,3.5,2056,232,0.17,815,2023-11-15
32,33,Headphones,Electronics,429.60,2.6,1696,919,0.43,1648,2024-02-27
33,34,Smartwatch,Electronics,294.54,2.5,98,152,0.00,1919,2023-07-08
34,35,Laptop,Electronics,349.03,3.6,4067,160,0.01,397,2023-09-07
35,36,Smartwatch,Electronics,375.78,3.6,1218,400,0.15,687,2024-05-19
36,37,Laptop,Electronics,299.04,4.9,562,437,0.45,26,2023-10-28
37,38,Smartphone,Electronics,256.29,3.3,959,480,0.10,1852,2023-08-11
38,39,Headphones,Electronics,290.28,4.1,16,171,0.47,476,2024-04-25
39,40,Smartphone,Electronics,442.91,4.0,1060,279,0.17,301,2023-12-12

In [40]:
df[df["Price"]>100]

,ProductID,ProductName,Category,Price,Rating,NumReviews,StockQuantity,Discount,Sales,DateAdded
0,1,Headphones,Electronics,400.31,1.7,3772,20,0.08,466,2023-11-08
1,2,Headphones,Electronics,235.03,2.3,2919,663,0.33,1332,2023-09-26
2,3,Smartwatch,Electronics,417.90,1.8,1184,459,0.31,252,2023-10-18
3,4,Smartphone,Electronics,152.70,3.4,2047,475,0.49,1806,2023-12-03
4,5,Laptop,Electronics,394.74,1.8,1267,831,0.23,1508,2023-08-08
...,...,...,...,...,...,...,...,...,...,...
994,995,Weighted Blanket,Blankets,269.34,3.3,2513,662,0.17,800,2023-10-23
995,996,Throw Blanket,Blankets,207.72,2.3,1973,16,0.46,325,2024-02-11
996,997,Fleece Blanket,Blankets,268.60,3.2,841,201,0.39,1546,2023-06-29
998,999,Weighted Blanket,Blankets,152.28,1.3,2850,752,0.34,1962,2023-10-26
999,1000,Throw Blanket,Blankets,136.53,2.0,4055,282,0.38,1089,2024-01-25

In [41]:
df["Price"].mean()

np.float64(253.77551)

In [46]:
df.max()

ProductID              1000
ProductName      Wool Socks
Category               Wine
Price                499.74
Rating                  5.0
NumReviews             4994
StockQuantity           993
Discount                0.5
Sales                  1997
DateAdded        2024-06-09
dtype: object

In [47]:
df.min()

ProductID                                 1
ProductName                   Action Figure
Category         Art and crafting materials
Price                                 10.11
Rating                                  1.0
NumReviews                                3
StockQuantity                             0
Discount                                0.0
Sales                                     0
DateAdded                        2023-06-12
dtype: object

In [51]:
df["ProductName"][df["StockQuantity"]>7]

0            Headphones
1            Headphones
2            Smartwatch
3            Smartphone
4                Laptop
             ...
995       Throw Blanket
996      Fleece Blanket
997       Throw Blanket
998    Weighted Blanket
999       Throw Blanket
Name: ProductName, Length: 993, dtype: object

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ProductID      1000 non-null   int64
 1   ProductName    1000 non-null   object
 2   Category       1000 non-null   object
 3   Price          1000 non-null   float64
 4   Rating         1000 non-null   float64
 5   NumReviews     1000 non-null   int64
 6   StockQuantity  1000 non-null   int64
 7   Discount       1000 non-null   float64
 8   Sales          1000 non-null   int64
 9   DateAdded      1000 non-null   object
dtypes: float64(3), int64(4), object(3)
memory usage: 78.3+ KB

In [53]:
df["Total Sales"]= df["Price"]*df["StockQuantity"]
df

,ProductID,ProductName,Category,Price,Rating,NumReviews,StockQuantity,Discount,Sales,DateAdded,Total Sales
0,1,Headphones,Electronics,400.31,1.7,3772,20,0.08,466,2023-11-08,8006.20
1,2,Headphones,Electronics,235.03,2.3,2919,663,0.33,1332,2023-09-26,155824.89
2,3,Smartwatch,Electronics,417.90,1.8,1184,459,0.31,252,2023-10-18,191816.10
3,4,Smartphone,Electronics,152.70,3.4,2047,475,0.49,1806,2023-12-03,72532.50
4,5,Laptop,Electronics,394.74,1.8,1267,831,0.23,1508,2023-08-08,328028.94
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Throw Blanket,Blankets,207.72,2.3,1973,16,0.46,325,2024-02-11,3323.52
996,997,Fleece Blanket,Blankets,268.60,3.2,841,201,0.39,1546,2023-06-29,53988.60
997,998,Throw Blanket,Blankets,92.74,2.8,3454,880,0.02,1295,2023-10-27,81611.20
998,999,Weighted Blanket,Blankets,152.28,1.3,2850,752,0.34,1962,2023-10-26,114514.56
999,1000,Throw Blanket,Blankets,136.53,2.0,4055,282,0.38,1089,2024-01-25,38501.46

In [54]:
df[["ProductName","Total Sales"]]

          ProductName  Total Sales
0          Headphones      8006.20
1          Headphones    155824.89
2          Smartwatch    191816.10
3          Smartphone     72532.50
4              Laptop    328028.94
..                ...          ...
995     Throw Blanket      3323.52
996    Fleece Blanket     53988.60
997     Throw Blanket     81611.20
998  Weighted Blanket    114514.56
999     Throw Blanket     38501.46

[1000 rows x 2 columns]

In [55]:
df["Total Sales"].sum()

np.float64(125454020.80000001)