In [1]:
import pandas as pd 
import numpy as np

In [3]:
data={
    "name":["kashish","khushi","kanan","vanshika"],
    "age":[20,21,22,23],
    "city":["pathankot","jalandhar","haryana","delhi"],
    "salary":[10000,20000,30000,np.nan]
    
}
data

{'name': ['kashish', 'khushi', 'kanan', 'vanshika'],
 'age': [20, 21, 22, 23],
 'city': ['pathankot', 'jalandhar', 'haryana', 'delhi'],
 'salary': [10000, 20000, 30000, nan]}

In [5]:
df=pd.DataFrame(data)
df

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [6]:
df["name"]

0     kashish
1      khushi
2       kanan
3    vanshika
Name: name, dtype: object

In [7]:
df.iloc[0]

name        kashish
age              20
city      pathankot
salary      10000.0
Name: 0, dtype: object

In [12]:
df.iloc[0:3,2:4]

        city   salary
0  pathankot  10000.0
1  jalandhar  20000.0
2    haryana  30000.0

In [13]:
df.head()

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [15]:
df.head(2)

      name  age       city   salary
0  kashish   20  pathankot  10000.0
1   khushi   21  jalandhar  20000.0

In [16]:
df.iloc[:4]

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [17]:
df.iloc[:]

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [18]:
df

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [20]:
df.loc[[2,3],["name","age"]]

       name  age
2     kanan   22
3  vanshika   23

In [22]:
df[df["age"]>20]

       name  age       city   salary
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [23]:
df.city=="delhi"

0    False
1    False
2    False
3     True
Name: city, dtype: bool

In [24]:
df[df.salary.isnull()]

       name  age   city  salary
3  vanshika   23  delhi     NaN

In [25]:
df[df["city"].isin(("delhi","haryana"))]

       name  age     city   salary
2     kanan   22  haryana  30000.0
3  vanshika   23    delhi      NaN

In [26]:
df.sort_values("age")

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [27]:
df.sort_values("age",ascending=False)

       name  age       city   salary
3  vanshika   23      delhi      NaN
2     kanan   22    haryana  30000.0
1    khushi   21  jalandhar  20000.0
0   kashish   20  pathankot  10000.0

In [29]:
df.sort_values(["age","city"])

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi      NaN

In [32]:
df.sort_values(by=["age","city"],ascending=[False,False])

       name  age       city   salary
3  vanshika   23      delhi      NaN
2     kanan   22    haryana  30000.0
1    khushi   21  jalandhar  20000.0
0   kashish   20  pathankot  10000.0

In [33]:
df.isnull()

    name    age   city  salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False    True

In [34]:
df.isnull().sum()

name      0
age       0
city      0
salary    1
dtype: int64

In [35]:
df.dropna()

      name  age       city   salary
0  kashish   20  pathankot  10000.0
1   khushi   21  jalandhar  20000.0
2    kanan   22    haryana  30000.0

In [39]:
df["salary"]=df["salary"].fillna(df["salary"].median())
df

       name  age       city   salary
0   kashish   20  pathankot  10000.0
1    khushi   21  jalandhar  20000.0
2     kanan   22    haryana  30000.0
3  vanshika   23      delhi  20000.0

In [38]:
df["city"].unique()

array(['pathankot', 'jalandhar', 'haryana', 'delhi'], dtype=object)

In [40]:
df["city"].nunique()

4

In [41]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [42]:
df[df["salary"].duplicated()]

       name  age   city   salary
3  vanshika   23  delhi  20000.0

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df["tax"]=df["salary"]*0.05
df

       name  age       city   salary     tax
0   kashish   20  pathankot  10000.0   500.0
1    khushi   21  jalandhar  20000.0  1000.0
2     kanan   22    haryana  30000.0  1500.0
3  vanshika   23      delhi  20000.0  1000.0

In [46]:
df["city"]=df["city"].str.upper()
df

       name  age       city   salary     tax
0   kashish   20  PATHANKOT  10000.0   500.0
1    khushi   21  JALANDHAR  20000.0  1000.0
2     kanan   22    HARYANA  30000.0  1500.0
3  vanshika   23      DELHI  20000.0  1000.0

In [50]:
df["name"]=df["name"].str.upper()
df

       name  age       city   salary     tax
0   KASHISH   20  PATHANKOT  10000.0   500.0
1    KHUSHI   21  JALANDHAR  20000.0  1000.0
2     KANAN   22    HARYANA  30000.0  1500.0
3  VANSHIKA   23      DELHI  20000.0  1000.0

In [51]:
df["experience"]=[1,2,3,4]
df

       name  age       city   salary     tax  experience
0   KASHISH   20  PATHANKOT  10000.0   500.0           1
1    KHUSHI   21  JALANDHAR  20000.0  1000.0           2
2     KANAN   22    HARYANA  30000.0  1500.0           3
3  VANSHIKA   23      DELHI  20000.0  1000.0           4

In [52]:
def salary_category(salary):
    if salary<10000:
        return "low"
    elif salary<20000:
        return "medium"
    else:
        return "high"
df["salary_category"]=df["salary"].apply(salary_category)
df

       name  age       city   salary     tax  experience salary_category
0   KASHISH   20  PATHANKOT  10000.0   500.0           1          medium
1    KHUSHI   21  JALANDHAR  20000.0  1000.0           2            high
2     KANAN   22    HARYANA  30000.0  1500.0           3            high
3  VANSHIKA   23      DELHI  20000.0  1000.0           4            high