In [1]:
import pandas as pd
import numpy as np

In [2]:
list=["h","i","b","s"]
list

['h', 'i', 'b', 's']

In [5]:
a=pd.Series(list)
a

0    h
1    i
2    b
3    s
dtype: object

In [7]:
labels=["a","b","c","d"]
a=pd.Series(list, index=labels)
a

a    h
b    i
c    b
d    s
dtype: object

In [8]:
a["c"]

'b'

In [9]:
a["d"]

's'

In [10]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
person={"name":"kanan","age":19,"country":"india"}
person

{'name': 'kanan', 'age': 19, 'country': 'india'}

In [13]:
b=pd.Series(arr)
b

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [15]:
c=pd.Series(person)
c

name       kanan
age           19
country    india
dtype: object

In [16]:
data={
    "name":["kanan","riya","mehak"],
    "age":[20,23,21],
    "city":["jalandhar","gurdaspur","amritsar"]
}
df=pd.DataFrame(data)
df

    name  age       city
0  kanan   20  jalandhar
1   riya   23  gurdaspur
2  mehak   21   amritsar

In [23]:
data=[
    ["kanan",20,"jalandhar"],
    ["riya",23,"gurdaspur"],
    ["mehak",21,"amritsar"]
]
column =["name","age","city"]
df=pd.DataFrame(data,columns=column)
df

    name  age       city
0  kanan   20  jalandhar
1   riya   23  gurdaspur
2  mehak   21   amritsar

In [24]:
df["name"]

0    kanan
1     riya
2    mehak
Name: name, dtype: object

In [25]:
df[["name","age"]]

    name  age
0  kanan   20
1   riya   23
2  mehak   21

In [26]:
df.loc[0]

name        kanan
age            20
city    jalandhar
Name: 0, dtype: object

In [27]:
df.loc[[0,1]]

    name  age       city
0  kanan   20  jalandhar
1   riya   23  gurdaspur

In [32]:
df.loc[[0,1],["age","city"]]

   age       city
0   20  jalandhar
1   23  gurdaspur

In [33]:
df[df["age"]>20]

    name  age       city
1   riya   23  gurdaspur
2  mehak   21   amritsar

In [34]:
df[df["age"]>20]["name"]

1     riya
2    mehak
Name: name, dtype: object

In [ ]:
df[(df["age"]> 20) &(df["city"]=="jalandhar")]

Empty DataFrame
Columns: [name, age, city]
Index: []

: