In [1]:
#assignment questions 
import numpy as np
import pandas as pd

In [2]:
list=[10,20,30,40]
print(pd.Series(list))

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
li=[100,200,300]
labels=["a","b","c"]
print(pd.Series(li,index=labels))

a    100
b    200
c    300
dtype: int64

In [4]:
dict={"x":5,"y":10,"z":15}
print(pd.Series(dict))

x     5
y    10
z    15
dtype: int64

In [5]:
print(dict["y"])

10

In [8]:
data = {
    "name": ["rahul", "priya", "amit", "neha"],
    "age": [22, 21, 23, 22],
    "city": ["pune", "mumbai", "nashik", "delhi"]
}
df=pd.DataFrame(data)
df

    name  age    city
0  rahul   22    pune
1  priya   21  mumbai
2   amit   23  nashik
3   neha   22   delhi

In [11]:
data1=[
    ["rahul",22,"pune"],
    ["priya",21,"mumbai"],
    ["amit",23,"nashik"],
    ["neha",22,"delhi"] 
]
columns=["name","age","city"]
df1=pd.DataFrame(data1, columns=columns)
df1

    name  age    city
0  rahul   22    pune
1  priya   21  mumbai
2   amit   23  nashik
3   neha   22   delhi

In [12]:
df["name"]

0    rahul
1    priya
2     amit
3     neha
Name: name, dtype: object

In [14]:
df[["name","city"]]

    name    city
0  rahul    pune
1  priya  mumbai
2   amit  nashik
3   neha   delhi

In [16]:
df.loc[[0,1]]

    name  age    city
0  rahul   22    pune
1  priya   21  mumbai

In [17]:
df.iloc[2]

name      amit
age         23
city    nashik
Name: 2, dtype: object

In [18]:
marks=[78,85,90,67]
df["marks"]=marks
df

    name  age    city  marks
0  rahul   22    pune     78
1  priya   21  mumbai     85
2   amit   23  nashik     90
3   neha   22   delhi     67

In [19]:
df["course"]=["python","java","python","data science"]
df

    name  age    city  marks        course
0  rahul   22    pune     78        python
1  priya   21  mumbai     85          java
2   amit   23  nashik     90        python
3   neha   22   delhi     67  data science

In [25]:
df2=df.drop(columns=["city"])
df2

    name  age  marks        course
0  rahul   22     78        python
1  priya   21     85          java
2   amit   23     90        python
3   neha   22     67  data science

In [26]:
df3=df.drop(index=1)
df3

    name  age    city  marks        course
0  rahul   22    pune     78        python
2   amit   23  nashik     90        python
3   neha   22   delhi     67  data science

In [28]:
df[df["age"]>22]

   name  age    city  marks  course
2  amit   23  nashik     90  python

In [29]:
df[df["city"]=="pune"]

    name  age  city  marks  course
0  rahul   22  pune     78  python

In [30]:
df[(df["age"]>21) & (df["city"] =="delhi")]

   name  age   city  marks        course
3  neha   22  delhi     67  data science