In [71]:
import pandas as pd 
import numpy as np

In [72]:
data={
    "dept": ["it","it","it","it","finance","hr"],
    "salary":[10000,20000,30000,40000,50000,60000],
    "employee":[1,2,3,4,5,6],
    "experience":[1,2,3,4,5,6]
}

In [73]:
df1 = pd.DataFrame(data)
df1

      dept  salary  employee  experience
0       it   10000         1           1
1       it   20000         2           2
2       it   30000         3           3
3       it   40000         4           4
4  finance   50000         5           5
5       hr   60000         6           6

In [74]:
avg_salary=df1.groupby("dept")["salary"].mean()
print(avg_salary)

dept
finance    50000.0
hr         60000.0
it         25000.0
Name: salary, dtype: float64

In [75]:
max_experience=df1.groupby("dept")["experience"].max()
print(max_experience)

dept
finance    5
hr         6
it         4
Name: experience, dtype: int64

In [76]:
total_salary=df1.groupby("dept")["salary"].sum()
total_salary

dept
finance     50000
hr          60000
it         100000
Name: salary, dtype: int64

In [77]:
employee_count = df1.groupby("dept")["employee"].count()
employee_count

dept
finance    1
hr         1
it         4
Name: employee, dtype: int64

In [78]:
average_salary_experience = df1.groupby("dept")[["salary","experience"]].mean()
average_salary_experience

          salary  experience
dept
finance  50000.0         5.0
hr       60000.0         6.0
it       25000.0         2.5

In [79]:
df1.groupby("dept").agg({"salary":["mean","sum"],"experience":["mean","max"],"employee":"count"})

          salary         experience     employee
            mean     sum       mean max    count
dept
finance  50000.0   50000        5.0   5        1
hr       60000.0   60000        6.0   6        1
it       25000.0  100000        2.5   4        4

In [80]:
employee =pd.DataFrame({
    "name":["a","b","c","d"],
    "emp_id":[1,2,3,4]
})

In [81]:
departments=pd.DataFrame({
    "emp_id":[1,2,3,4],
    "dept":["it","hr","finance","it"]
})

In [82]:
inner_merge = pd.merge(employee, departments, left_on='email_id', right_on='emp_id', how='inner')
inner_merge

KeyError: 'email_id'

In [ ]:
df1= pd.DataFrame({
    "name":["a","b","c","d"],
    "email_id":[1,2,3,4]
})
df2=pd.DataFrame({
    "name":["e","f","g","h"],
    "email_id":[5,6,7,8]
})
row_concat = pd.concat([df1,df2])
row_concat

  name  email_id
0    a         1
1    b         2
2    c         3
3    d         4
0    e         5
1    f         6
2    g         7
3    h         8

In [ ]:
df=pd.concat([df1,df2],ignore_index=True)
df

  name  email_id
0    a         1
1    b         2
2    c         3
3    d         4
4    e         5
5    f         6
6    g         7
7    h         8

In [ ]:
column_concatenate= pd.concat([df1,df2],axis=1,ignore_index=True)
column_concatenate

   0  1  2  3
0  a  1  e  5
1  b  2  f  6
2  c  3  g  7
3  d  4  h  8

In [ ]:
concate_keys=pd.concat([df1,df2],keys=["df1","df2"])
concate_keys

      name  email_id
df1 0    a         1
    1    b         2
    2    c         3
    3    d         4
df2 0    e         5
    1    f         6
    2    g         7
    3    h         8

In [84]:
p=pd.pivot_table(df,index="name",values="email_id",aggfunc="sum")
p

      email_id
name
a            1
b            2
c            3
d            4
e            5
f            6
g            7
h            8

In [86]:
products=pd.DataFrame({
    "product_id":[1,2,3,4],
    "product_name":["a","b","c","d"],
    "price":[100,200,300,400],
    "product_sold":[10,20,30,40]
})

sales=pd.DataFrame({
    "product_id":[1,2,3,4],
    "quantity_sold":[10,20,30,40]
})
result=pd.merge(products,sales)
result

   product_id product_name  price  product_sold  quantity_sold
0           1            a    100            10             10
1           2            b    200            20             20
2           3            c    300            30             30
3           4            d    400            40             40

In [ ]:
total_sales=pd.pivot_table(result,index="product_name",values="quantity_sold",aggfunc="sum")
total_sales

              quantity_sold
product_name
a                        10
b                        20
c                        30
d                        40