In [1]:
import pandas as pd
import numpy as np

In [2]:
data={
    "department":["it","it","it","it","finance","hr"],
    "salary":[10000,20000,30000,40000,50000,60000],
    "employee":[1,2,3,4,5,6],
    "experience":[1,2,3,4,5,6]
}
df=pd.DataFrame(data)
df

  department  salary  employee  experience
0         it   10000         1           1
1         it   20000         2           2
2         it   30000         3           3
3         it   40000         4           4
4    finance   50000         5           5
5         hr   60000         6           6

In [3]:
#groupby
avg_salary=df.groupby("department")["salary"].mean()
avg_salary

department
finance    50000.0
hr         60000.0
it         25000.0
Name: salary, dtype: float64

In [4]:
max_salary=df.groupby("department")["salary"].max()
max_salary

department
finance    50000
hr         60000
it         40000
Name: salary, dtype: int64

In [5]:
total_salary=df.groupby("department")["salary"].sum()
total_salary

department
finance     50000
hr          60000
it         100000
Name: salary, dtype: int64

In [6]:
emp_count= df.groupby("department")["employee"].count()
emp_count

department
finance    1
hr         1
it         4
Name: employee, dtype: int64

In [7]:
avg_salary_experience= df.groupby("department")[["salary","experience"]].mean()
avg_salary_experience

             salary  experience
department
finance     50000.0         5.0
hr          60000.0         6.0
it          25000.0         2.5

In [8]:
#merge &join
employee =pd.DataFrame({
    "id":[1,2,3,4],
    "name":["a","b","c","d"],
    "department":["it","it","hr","hr"]
})
departemnts=pd.DataFrame({
    "id":[1,2,3,4],
    "salary":[10000,20000,30000,40000],
    "department":["it","hr","finance","it"]
})
result=pd.merge(employee,departemnts,on="id")
result

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [9]:
inner_join =pd.merge(employee,departemnts,how="inner",on="id")
inner_join

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [10]:
left_join=pd.merge(employee,departemnts,how="left",on="id")
left_join

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [11]:
right_join=pd.merge(employee,departemnts,how="right",on="id")
right_join

   id name department_x  salary department_y
0   1    a           it   10000           it
1   2    b           it   20000           hr
2   3    c           hr   30000      finance
3   4    d           hr   40000           it

In [12]:
#find records exist in one only 
merged=pd.merge(employee,departemnts,how="outer",indicator=True)
merged

   id name department   salary      _merge
0   1    a         it  10000.0        both
1   2  NaN         hr  20000.0  right_only
2   2    b         it      NaN   left_only
3   3  NaN    finance  30000.0  right_only
4   3    c         hr      NaN   left_only
5   4    d         hr      NaN   left_only
6   4  NaN         it  40000.0  right_only

In [16]:
#concatenation 
df1=pd.DataFrame({
    "id":[1,2,3,4],
    "name":["a","b","c","d"],
    "salary":[10000,20000,30000,40000],
    "department":["it","it","hr","hr"]
})
df2=pd.DataFrame({
    "id":[1,2,3,4],
    "name":["e","f","g","h"],
    "salary":[50000,60000,70000,80000],
    "department":["it","it","hr","hr"]
})
row_concat=pd.concat([df1,df2])
row_concat

   id name  salary department
0   1    a   10000         it
1   2    b   20000         it
2   3    c   30000         hr
3   4    d   40000         hr
0   1    e   50000         it
1   2    f   60000         it
2   3    g   70000         hr
3   4    h   80000         hr

In [17]:
column_concat=pd.concat([df1,df2],axis=1)
column_concat

   id name  salary department  id name  salary department
0   1    a   10000         it   1    e   50000         it
1   2    b   20000         it   2    f   60000         it
2   3    c   30000         hr   3    g   70000         hr
3   4    d   40000         hr   4    h   80000         hr

In [18]:
concatenate = pd.concat([df1,df2],ignore_index=True)
concatenate

   id name  salary department
0   1    a   10000         it
1   2    b   20000         it
2   3    c   30000         hr
3   4    d   40000         hr
4   1    e   50000         it
5   2    f   60000         it
6   3    g   70000         hr
7   4    h   80000         hr

In [19]:
keys_concat=pd.concat([df1,df2],keys=["df1","df2"])
keys_concat

       id name  salary department
df1 0   1    a   10000         it
    1   2    b   20000         it
    2   3    c   30000         hr
    3   4    d   40000         hr
df2 0   1    e   50000         it
    1   2    f   60000         it
    2   3    g   70000         hr
    3   4    h   80000         hr